### ISSUE TITLE
Is the paper published?

### ISSUE THREAD

**Issue by knsjoon** [Cameltr/TransRef#1]
I would like to read your paper.
So I wonder if I can find it or access it somehow. 
And also regarding code, is it complete version?

Thank you for great work.

**Comment by Cameltr** [comment]
Sorry, this paper is currently under review and has not been published yet. Meanwhile, the code for the paper is not yet the final version.  Once the paper is accepted, I will immediately update the github repository! Thank you for your attention!

**Comment by knsjoon** [comment]
@Cameltr Thank you for answering! I appreciate a lot. 
May I ask when the paper review will be finalized?
And so if I train on my own dataset with the current code (as I struggled on downloading the dataset from Baidu as I do not have an account), it is not going to work right?

**Comment by Cameltr** [comment]
1.After the review comments of the paper in the first review stage are returned, we will publish the paper on arxiv. Due to the long review cycle of the journal,  it will take another one or two months to wait. 
2.As for the second question, because our method is trained on preprocessed image pairs which are cropped based on sift feature matching algorithm, it may not perform well on your own dataset. I will upload our dataset to Google Cloud when I am free.

**Comment by knsjoon** [comment]
@Cameltr I see that you did upload the dataset through google drive. Thank you very much!!
Looking forward to read your paper! Wish you a lot of luck for your paper result!!

**Comment by Cameltr** [comment]
Hello, the preprinted paper has been published to arxiv. Thanks for your attention！
