### ISSUE TITLE
Network framework layers

### ISSUE THREAD

**Issue by LYL-hub-source** [Cameltr/TransRef#6]
Hello, thank you for your contribution, I would like to know why the coding stage of the model was chosen to be three layers instead of more, was it because the number of parameters was too large due to the increase in the number of layers of the network, or was there some other reason?

**Comment by Cameltr** [comment]
This is due to the limitations related to the size of the feature maps. By the time the model reaches the third layer, the feature maps have already become quite small. We believe that going into the fourth layer would result in too much information loss due to downsampling, so the network is designed with only three layers.

**Comment by LYL-hub-source** [comment]
I see. Thanks for the answer.
